version: "3"

services: 
  db:
    image: postgres
    container_name: postgresql
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data:rw