version: "3"

services: 
  db:
    image: mysql
    container_name: MYSQL
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "admin"
    volumes: 
      - ./schemas:/var/lib/mysql:rw
    networks: 
      mysql_network:
        aliases: 
          - mysql_host
volumes: 
  schemas: {}
networks: 
  mysql_network:
    name: mysql_net
    driver: bridge