version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: "0:0"
    hostname: sql-server
    container_name: sql-server
    environment:
      SA_PASSWORD: Admin123
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - ./backups:/var/backups:rw